// Installs the mod from the zip it came in.
//
// The TrackMania ModLoader has no "mods folder" to drop a DLL into: it keeps a
// product database under %LOCALAPPDATA%\TMLoader, a folder per mod and a folder
// per version inside it, each with a small description.yaml. Nobody should have
// to know that.
//
// The zip already holds that folder, ready - "100% TMX + Bingo", exactly as the
// ModLoader wants it - and this copies it into place. That is all it does.
//
// It used to carry the DLL inside itself as a resource and write it out, which
// is the textbook shape of a malware dropper, and Microsoft Defender's
// machine-learning detection called it one (Trojan:Win32/Wacatac!ml) on every
// release. Copying a folder that sits in plain sight next to the program is the
// same install without the shape - and the folder can be copied by hand just as
// well, which README.txt in the zip says. No network, no dependencies, one
// dialog either way.
//
//   100TMX-Installer.exe              install, with a confirmation dialog
//   100TMX-Installer.exe /quiet       install, say nothing unless it fails
//   100TMX-Installer.exe /uninstall   remove the product folder again
#include <windows.h>
#include <shlobj.h>
#include <shellapi.h>

#include <string>

#include "tmx_version.h"

#pragma comment(lib, "shell32.lib")
#pragma comment(lib, "ole32.lib")

namespace {

const wchar_t* kTitle = L"100% TMX + Bingo";
const wchar_t* kVersion = TMX_VERSION;  // tmx_version.h, generated by CMake

// The ModLoader's list shows the product *folder*, not the name inside its
// description.yaml - that one only appears in the details panel. So the folder
// is what has to read like the mod's name, and the id in a profile is this same
// string, which is why renaming it has to carry the profiles along.
const wchar_t* kProduct = L"100% TMX + Bingo";
const wchar_t* kOldProducts[] = {L"100TMX"};
const wchar_t* kModLoaderPage = L"https://tomashu.dev/software/tmloader/";

std::wstring localAppData() {
  wchar_t* raw = nullptr;
  std::wstring out;
  if (SUCCEEDED(SHGetKnownFolderPath(FOLDERID_LocalAppData, 0, nullptr, &raw)) && raw) out = raw;
  if (raw) CoTaskMemFree(raw);
  return out;
}

std::string wide(const std::wstring& in) {
  if (in.empty()) return std::string();
  int size = WideCharToMultiByte(CP_UTF8, 0, in.c_str(), static_cast<int>(in.size()), nullptr, 0, nullptr, nullptr);
  std::string out(static_cast<size_t>(size), '\0');
  WideCharToMultiByte(CP_UTF8, 0, in.c_str(), static_cast<int>(in.size()), &out[0], size, nullptr, nullptr);
  return out;
}

// The folder this program was started from - where the zip put
// "100% TMX + Bingo" next to it.
std::wstring ownDirectory() {
  wchar_t path[MAX_PATH]{};
  const DWORD length = GetModuleFileNameW(nullptr, path, MAX_PATH);
  if (length == 0 || length >= MAX_PATH) return std::wstring();
  std::wstring out(path, length);
  const size_t slash = out.find_last_of(L"\\/");
  return slash == std::wstring::npos ? std::wstring() : out.substr(0, slash);
}

bool exists(const std::wstring& path) {
  return GetFileAttributesW(path.c_str()) != INVALID_FILE_ATTRIBUTES;
}

// Copies the product folder: its files, and one level of version folders with
// their files. Exactly the shape the ModLoader uses and nothing deeper -
// bounded on purpose, like the removal below.
bool copyProduct(const std::wstring& from, const std::wstring& to, int depth = 0) {
  SHCreateDirectoryExW(nullptr, to.c_str(), nullptr);
  WIN32_FIND_DATAW find{};
  HANDLE handle = FindFirstFileW((from + L"\\*").c_str(), &find);
  if (handle == INVALID_HANDLE_VALUE) return false;
  bool ok = true;
  do {
    const std::wstring name = find.cFileName;
    if (name == L"." || name == L"..") continue;
    const std::wstring source = from + L"\\" + name;
    const std::wstring target = to + L"\\" + name;
    if (find.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY) {
      if (depth < 1) ok = copyProduct(source, target, depth + 1) && ok;
    } else {
      ok = CopyFileW(source.c_str(), target.c_str(), FALSE) && ok;
    }
  } while (FindNextFileW(handle, &find));
  FindClose(handle);
  return ok;
}

// Removes a directory and what is in it, one level deep - which is all this
// ever creates. Deliberately not recursive: an uninstaller that walks a tree is
// an uninstaller that can delete the wrong tree.
void removeVersionDir(const std::wstring& dir) {
  WIN32_FIND_DATAW find{};
  HANDLE handle = FindFirstFileW((dir + L"\\*").c_str(), &find);
  if (handle != INVALID_HANDLE_VALUE) {
    do {
      const std::wstring name = find.cFileName;
      if (name == L"." || name == L"..") continue;
      if (find.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY) {
        removeVersionDir(dir + L"\\" + name);
      } else {
        DeleteFileW((dir + L"\\" + name).c_str());
      }
    } while (FindNextFileW(handle, &find));
    FindClose(handle);
  }
  RemoveDirectoryW(dir.c_str());
}

bool g_quiet = false;

// Quiet means quiet, including when it goes wrong: a silent install that stops
// to argue in a dialog is not silent, and the exit code already carries it.
// Rewrite the mod's id where a profile has it ticked.
//
// A profile lists mods by id, and the id is the folder name - so renaming the
// folder without this would quietly untick the mod for anybody who already had
// it on, and leave them wondering why it stopped loading. Passing an empty
// `to` removes the line instead, which is what uninstalling wants.
void renameInProfiles(const std::wstring& loader, const std::wstring& to, const std::wstring& alsoRemove) {
  const std::wstring dir = loader + L"\\database\\TmForever\\profiles";

  WIN32_FIND_DATAW find{};
  HANDLE handle = FindFirstFileW((dir + L"\\*.yaml").c_str(), &find);
  if (handle == INVALID_HANDLE_VALUE) return;

  do {
    const std::wstring path = dir + L"\\" + find.cFileName;

    std::string text;
    {
      HANDLE file = CreateFileW(path.c_str(), GENERIC_READ, FILE_SHARE_READ, nullptr, OPEN_EXISTING,
                                FILE_ATTRIBUTE_NORMAL, nullptr);
      if (file == INVALID_HANDLE_VALUE) continue;
      char buffer[8192];
      DWORD read = 0;
      while (ReadFile(file, buffer, sizeof(buffer), &read, nullptr) && read > 0) text.append(buffer, read);
      CloseHandle(file);
    }
    if (text.empty() || text.size() > 64 * 1024) continue;

    const std::string wanted = wide(to);
    bool changed = false;
    for (const wchar_t* old : kOldProducts) {
      const std::string needle = "id: " + wide(old);
      size_t at = text.find(needle);
      while (at != std::string::npos) {
        // Only a whole id: "100TMX" must not match inside "100TMX Legacy".
        const size_t after = at + needle.size();
        const bool wholeLine = after >= text.size() || text[after] == '\n' || text[after] == '\r';
        if (wholeLine) {
          text.replace(at, needle.size(), alsoRemove.empty() ? ("id: '" + wanted + "'") : std::string("id: __removed__"));
          changed = true;
        }
        at = text.find(needle, at + 1);
      }
    }
    if (!changed) continue;

    HANDLE file = CreateFileW(path.c_str(), GENERIC_WRITE, 0, nullptr, CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, nullptr);
    if (file == INVALID_HANDLE_VALUE) continue;
    DWORD written = 0;
    WriteFile(file, text.data(), static_cast<DWORD>(text.size()), &written, nullptr);
    CloseHandle(file);
  } while (FindNextFileW(handle, &find));

  FindClose(handle);
}

int say(const std::wstring& text, UINT icon = MB_ICONINFORMATION) {
  if (g_quiet) return IDOK;
  return MessageBoxW(nullptr, text.c_str(), kTitle, MB_OK | icon);
}

}  // namespace

int WINAPI wWinMain(HINSTANCE, HINSTANCE, PWSTR commandLine, int) {
  const std::wstring args = commandLine ? commandLine : L"";
  const bool quiet = args.find(L"/quiet") != std::wstring::npos;
  g_quiet = quiet;
  const bool uninstall = args.find(L"/uninstall") != std::wstring::npos;

  const std::wstring local = localAppData();
  if (local.empty()) {
    say(L"Could not find your AppData folder, which is where the ModLoader keeps its mods.", MB_ICONERROR);
    return 1;
  }

  const std::wstring loader = local + L"\\TMLoader";
  const std::wstring products = loader + L"\\database\\TmForever\\products";
  const std::wstring product = products + L"\\" + kProduct;

  if (uninstall) {
    removeVersionDir(product);
    for (const wchar_t* old : kOldProducts) removeVersionDir(products + L"\\" + old);
    renameInProfiles(loader, kProduct, L"");
    if (!quiet) say(L"100% TMX + Bingo has been removed from the ModLoader.\n\nYour settings in Documents\\100TMX are left alone.");
    return 0;
  }

  if (GetFileAttributesW(loader.c_str()) == INVALID_FILE_ATTRIBUTES) {
    const int answer = MessageBoxW(nullptr,
                                   L"The TrackMania ModLoader does not seem to be installed.\n\n"
                                   L"This mod is loaded by it, so it has to come first.\n\n"
                                   L"Open the ModLoader's download page now?",
                                   kTitle, MB_YESNO | MB_ICONWARNING);
    if (answer == IDYES) ShellExecuteW(nullptr, L"open", kModLoaderPage, nullptr, nullptr, SW_SHOWNORMAL);
    return 1;
  }

  // The folder the zip put next to this program. Missing almost always means
  // it was started from inside the zip without unpacking it - Windows then
  // extracts this one file to a temporary folder and nothing else.
  const std::wstring source = ownDirectory() + L"\\" + kProduct;
  if (!exists(source + L"\\description.yaml")) {
    say(L"The folder \"100% TMX + Bingo\" is not next to this installer.\n\n"
        L"Unzip the whole zip first (right-click it, \"Extract All...\"), then run "
        L"100TMX-Installer.exe from the unzipped folder.",
        MB_ICONERROR);
    return 1;
  }

  // An older install sat under a different folder name, which is also the id a
  // profile ticked. Move both across before writing, so an update keeps working
  // instead of silently switching itself off.
  for (const wchar_t* old : kOldProducts) {
    const std::wstring previous = products + L"\\" + old;
    if (exists(previous)) removeVersionDir(previous);
  }
  renameInProfiles(loader, kProduct, L"");

  // Older *versions* of this product are deliberately left alone. Deleting
  // them tidies the ModLoader's list, and it also breaks every profile that
  // has this mod ticked at the version being removed: the loader resolves a
  // profile by product *and* version, and a missing one fails the whole launch
  // with "failed to find required products to resolve their dependencies" -
  // the game will not start at all. Copying merges, so they stay.
  const bool ok = copyProduct(source, product);

  if (!ok) {
    say(L"Could not write into the ModLoader's folder.\n\n"
        L"If TrackMania is running, close it and try again.",
        MB_ICONERROR);
    return 1;
  }

  if (!quiet) {
    say(std::wstring(L"100% TMX + Bingo ") + kVersion + L" is installed.\n\n"
        L"1. Open the TrackMania ModLoader\n"
        L"2. Tick \"100% TMX + Bingo\" in the list\n"
        L"3. Start the game\n\n"
        L"Then: Connect on the panel, or press F9 for the settings window.");
  }
  return 0;
}
